-- NayaFlow user-data.db schema, recovered from NayaFlow 1.25.1
-- Source: %APPDATA%/NayaFlow/user-data.db, 2026-08-28
-- Managed by goose migrations inside flow-bg-server.exe; queries generated by sqlc.

CREATE TABLE color_palettes (
	order_id integer NOT NULL,
	name text NOT NULL,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL
);

CREATE TABLE color_swatches (
	color_hex text,
	order_id integer NOT NULL,
	palette_id text,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	FOREIGN KEY (palette_id) REFERENCES color_palettes(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE dynamic_layer_groups (
	name text NOT NULL,
	order_id integer DEFAULT -1 NOT NULL,
	icon_id text,
	state text NOT NULL,
	author_name text,
	description text,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL
);

CREATE TABLE dynamic_layers (
	name text NOT NULL,
	order_id integer DEFAULT -1 NOT NULL,
	icon_id text,
	dynamic_layer_group_id text,
	author_name text,
	description text,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	FOREIGN KEY (dynamic_layer_group_id) REFERENCES dynamic_layer_groups(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE goose_db_version (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		version_id INTEGER NOT NULL,
		is_applied INTEGER NOT NULL,
		tstamp TIMESTAMP DEFAULT (datetime('now'))
	);

CREATE TABLE "key_bindings" (
	context text,
	action_code text NOT NULL,
	action_type text NOT NULL,
	behavior text NOT NULL,
	key_id text NOT NULL,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	FOREIGN KEY (key_id) REFERENCES keys(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE keys (
	color_hex text,
	position_id integer NOT NULL,
	layer_id text,
	dynamic_layer_id text,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	FOREIGN KEY (layer_id) REFERENCES layers(id) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (dynamic_layer_id) REFERENCES dynamic_layers(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE layers (
	name text NOT NULL,
	order_id integer DEFAULT -1 NOT NULL,
	icon_id text,
	profile_id text,
	author_name text,
	description text,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL, animation_id TEXT,
	FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE loop_action_macro_steps (
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	order_id integer NOT NULL,
	delay integer DEFAULT 30 NOT NULL,
	correlation_id text,
	macro_id text NOT NULL,
	boundary text NOT NULL,
	iteration integer NOT NULL,
	FOREIGN KEY (macro_id) REFERENCES macros(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE macros (
	name text NOT NULL,
	type text,
	icon_id text,
	order_id integer DEFAULT -1 NOT NULL,
	duration integer,
	size integer,
	author_name text,
	description text,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL
);

CREATE TABLE "module_bindings" (
	action_id text,
	action_code text,
	action_type text,
	behavior text NOT NULL,
	invert integer DEFAULT false NOT NULL,
	threshold integer DEFAULT 0 NOT NULL,
	direction text DEFAULT '+' NOT NULL,
	mode integer NOT NULL,
	module_config_id text NOT NULL,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	FOREIGN KEY (module_config_id) REFERENCES module_configs(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE "module_config_bindings" (
	profile_id text,
	layer_id text NOT NULL,
	module_config_id text,
	binding_location text NOT NULL,
	state text, -- "transparent", "disabled"
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	PRIMARY KEY(layer_id, binding_location),
	FOREIGN KEY (profile_id) REFERENCES profiles(id) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (layer_id) REFERENCES layers(id) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (module_config_id) REFERENCES module_configs(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE module_configs (
	name text NOT NULL,
	order_id integer DEFAULT -1 NOT NULL,
	icon_id text,
	author_name text,
	description text,
	size integer NOT NULL,
	type text NOT NULL,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL
);

CREATE TABLE "module_settings" (
    value TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'string',
    correlation_id TEXT NOT NULL,
    module_config_id TEXT NOT NULL,
    updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
    created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
    FOREIGN KEY (module_config_id) REFERENCES module_configs(id) ON UPDATE no action ON DELETE no action,
    PRIMARY KEY (correlation_id, module_config_id)
);

CREATE TABLE mouse_action_macro_steps (
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	order_id integer NOT NULL,
	delay integer DEFAULT 30 NOT NULL,
	correlation_id text,
	macro_id text NOT NULL,
	mouse_action_code text NOT NULL,
	state text NOT NULL,
	FOREIGN KEY (macro_id) REFERENCES macros(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE profiles (
	name text NOT NULL,
	order_id integer DEFAULT -1 NOT NULL,
	state text NOT NULL,
	icon_id text,
	author_name text,
	description text,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL
);

CREATE TABLE "settings" (
    value TEXT NOT NULL,
    correlation_id TEXT PRIMARY KEY NOT NULL,
    type TEXT NOT NULL DEFAULT 'string',
    created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
    updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL
);

CREATE TABLE sqlite_sequence(name,seq);

CREATE TABLE standard_action_macro_steps (
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	order_id integer NOT NULL,
	delay integer DEFAULT 30 NOT NULL,
	correlation_id text,
	macro_id text NOT NULL,
	action_code text NOT NULL,
	state text NOT NULL,
	FOREIGN KEY (macro_id) REFERENCES macros(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE templates (
	name text NOT NULL,
	description text,
	rate real DEFAULT 0 NOT NULL,
	icon_id text,
	order_id integer NOT NULL,
	creator_name text NOT NULL,
	creator_id text,
	downloads integer NOT NULL,
	entity_type text NOT NULL,
	entity_id text NOT NULL,
	is_default integer DEFAULT false NOT NULL,
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL
);

CREATE TABLE text_action_macro_steps (
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	order_id integer NOT NULL,
	delay integer DEFAULT 30 NOT NULL,
	macro_id text NOT NULL,
	input text NOT NULL,
	FOREIGN KEY (macro_id) REFERENCES macros(id) ON UPDATE no action ON DELETE no action
);

CREATE TABLE wait_for_release_macro_steps (
	id text PRIMARY KEY NOT NULL,
	updated_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	created_at TEXT DEFAULT (datetime('subsec')) NOT NULL,
	order_id integer NOT NULL,
	delay integer DEFAULT 30 NOT NULL,
	macro_id text NOT NULL,
	FOREIGN KEY (macro_id) REFERENCES macros(id) ON UPDATE no action ON DELETE no action
);
